import { pool, isPostgresAvailable } from '../pool';
import { AnalysisResult } from '../../types/shared';

// UUID generation helper for InMemory database fallback
function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

// Interfaces
export interface DbUser {
  id: string;
  email: string;
  name: string;
  created_at: string;
}

export interface DbVideo {
  id: string;
  user_id: string | null;
  filename: string;
  duration: number | null;
  created_at: string;
}

export interface DbAnalysis {
  id: string;
  video_id: string | null;
  vpi: number;
  classification: string;
  analysis_json: AnalysisResult;
  created_at: string;
  filename?: string;
}

// In-Memory Fallback Storage
const inMemoryUsers: DbUser[] = [];
const inMemoryVideos: DbVideo[] = [];
const inMemoryAnalyses: DbAnalysis[] = [];

// Seed Demo User in Memory
const DEMO_USER: DbUser = {
  id: '00000000-0000-0000-0000-000000000000',
  email: 'demo@viralytics.ai',
  name: 'Demo Creator',
  created_at: new Date().toISOString()
};
inMemoryUsers.push(DEMO_USER);

export const usersRepo = {
  async getOrCreateDemoUser(): Promise<DbUser> {
    if (isPostgresAvailable && pool) {
      try {
        const checkRes = await pool.query('SELECT * FROM users WHERE email = $1', [DEMO_USER.email]);
        if (checkRes.rows.length > 0) {
          return checkRes.rows[0];
        }
        const insertRes = await pool.query(
          'INSERT INTO users (id, email, name, created_at) VALUES ($1, $2, $3, $4) RETURNING *',
          [DEMO_USER.id, DEMO_USER.email, DEMO_USER.name, DEMO_USER.created_at]
        );
        return insertRes.rows[0];
      } catch (err) {
        console.error('Error in usersRepo.getOrCreateDemoUser (Postgres):', err);
      }
    }
    return DEMO_USER;
  }
};

export const videosRepo = {
  async create(userId: string | null, filename: string, duration: number | null): Promise<DbVideo> {
    const createdAt = new Date().toISOString();
    if (isPostgresAvailable && pool) {
      try {
        const id = generateUUID();
        const res = await pool.query(
          'INSERT INTO videos (id, user_id, filename, duration, created_at) VALUES ($1, $2, $3, $4, $5) RETURNING *',
          [id, userId, filename, duration, createdAt]
        );
        return res.rows[0];
      } catch (err) {
        console.error('Error in videosRepo.create (Postgres):', err);
      }
    }

    const newVideo: DbVideo = {
      id: generateUUID(),
      user_id: userId,
      filename,
      duration,
      created_at: createdAt
    };
    inMemoryVideos.push(newVideo);
    return newVideo;
  }
};

export const analysesRepo = {
  async create(videoId: string | null, vpi: number, classification: string, analysisJson: AnalysisResult): Promise<DbAnalysis> {
    const createdAt = new Date().toISOString();
    const id = analysisJson.id; // use the deterministic ID generated by provider

    if (isPostgresAvailable && pool) {
      try {
        // Check if analysis already exists to avoid duplicates (e.g. reseeding)
        const checkRes = await pool.query('SELECT * FROM analyses WHERE id = $1', [id]);
        if (checkRes.rows.length > 0) {
          return checkRes.rows[0];
        }
        const res = await pool.query(
          'INSERT INTO analyses (id, video_id, vpi, classification, analysis_json, created_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',
          [id, videoId, vpi, classification, JSON.stringify(analysisJson), createdAt]
        );
        return res.rows[0];
      } catch (err) {
        console.error('Error in analysesRepo.create (Postgres):', err);
      }
    }

    const existingIdx = inMemoryAnalyses.findIndex(a => a.id === id);
    if (existingIdx !== -1) {
      return inMemoryAnalyses[existingIdx];
    }

    const newAnalysis: DbAnalysis = {
      id,
      video_id: videoId,
      vpi,
      classification,
      analysis_json: analysisJson,
      created_at: createdAt
    };
    inMemoryAnalyses.push(newAnalysis);
    return newAnalysis;
  },

  async get(id: string): Promise<DbAnalysis | null> {
    if (isPostgresAvailable && pool) {
      try {
        const res = await pool.query(
          'SELECT a.*, v.filename FROM analyses a LEFT JOIN videos v ON a.video_id = v.id WHERE a.id = $1',
          [id]
        );
        if (res.rows.length > 0) {
          const row = res.rows[0];
          const analysis_json = typeof row.analysis_json === 'string' ? JSON.parse(row.analysis_json) : row.analysis_json;
          return {
            ...row,
            vpi: parseFloat(row.vpi),
            analysis_json,
          };
        }
        return null;
      } catch (err) {
        console.error('Error in analysesRepo.get (Postgres):', err);
      }
    }

    const found = inMemoryAnalyses.find(a => a.id === id);
    if (found) {
      const v = inMemoryVideos.find(vid => vid.id === found.video_id);
      return {
        ...found,
        filename: v ? v.filename : 'unknown-video.mp4'
      };
    }
    return null;
  },

  async list(): Promise<DbAnalysis[]> {
    if (isPostgresAvailable && pool) {
      try {
        const res = await pool.query(
          'SELECT a.*, v.filename FROM analyses a LEFT JOIN videos v ON a.video_id = v.id ORDER BY a.created_at DESC'
        );
        return res.rows.map(row => {
          const analysis_json = typeof row.analysis_json === 'string' ? JSON.parse(row.analysis_json) : row.analysis_json;
          return {
            ...row,
            vpi: parseFloat(row.vpi),
            analysis_json,
          };
        });
      } catch (err) {
        console.error('Error in analysesRepo.list (Postgres):', err);
      }
    }

    return inMemoryAnalyses.map(a => {
      const v = inMemoryVideos.find(vid => vid.id === a.video_id);
      return {
        ...a,
        filename: v ? v.filename : 'unknown-video.mp4'
      };
    }).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  }
};
